// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serve

import (
	"woh/internal/domain/manager"
	"woh/internal/provide/repo"
	"woh/internal/provide/secrets"
	"woh/package/actor"
	"woh/package/actor/sql/pgx"
	"woh/package/actor/third/gps"
	"woh/package/actor/third/gps/sub"
	"woh/webhooks/grpc"
	"woh/webhooks/http"
	"woh/webhooks/subs"
)

// Injectors from wire.go:

func Adapters() actor.Actors {
	provider := secrets.New()
	options := pgx.ProvideOptions()
	repoProvider := repo.New(options)
	service := manager.New(provider, repoProvider)
	adapter := http.New(service)
	grpcAdapter := grpc.New(service)
	subscriberConfig := sub.ProvideOptions()
	loggerAdapter := gps.ProvideLogger()
	subOptions := sub.Options{
		Config: subscriberConfig,
		Logger: loggerAdapter,
	}
	subsAdapter := subs.New(service, subOptions)
	actors := ChooseAdapters(adapter, grpcAdapter, subsAdapter)
	return actors
}
