// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"woh/package/actor"
	"woh/package/actor/sql/pgx"
	"woh/webhooks/adapt/cron"
	"woh/webhooks/provide/repo"
	"woh/webhooks/provide/secrets"
)

// Injectors from wire.go:

func Adapters() actor.Actors {
	options := pgx.ProvideOptions()
	provider := repo.New(options)
	secretsProvider := secrets.New()
	handler := &cron.Handler{
		Repo:    provider,
		Secrets: secretsProvider,
	}
	cronOptions := cron.Options{
		Handler: handler,
	}
	adapter := cron.New(cronOptions)
	actors := ChooseAdapters(adapter)
	return actors
}
