// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"github.com/andrestielau/web-of-hooks/internal/domain/worker"
	"github.com/andrestielau/web-of-hooks/internal/provide/repo"
	"github.com/andrestielau/web-of-hooks/internal/provide/secrets"
	"github.com/andrestielau/web-of-hooks/package/actor"
	"github.com/andrestielau/web-of-hooks/package/actor/sql/pgx"
	"github.com/andrestielau/web-of-hooks/webhooks/cron"
)

// Injectors from wire.go:

func Adapters() actor.Actors {
	provider := secrets.New()
	options := pgx.ProvideOptions()
	repoProvider := repo.New(options)
	service := worker.New(provider, repoProvider)
	adapter := cron.New(service)
	actors := ChooseAdapters(adapter)
	return actors
}
