// Code generated by pggen. DO NOT EDIT.

package queries

import (
	"context"
	"fmt"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	// CreateApplications inserts applications into the database
	CreateApplications(ctx context.Context, applications []NewApplication) ([]CreateApplicationsRow, error)

	// ListApplications lists registered applications
	ListApplications(ctx context.Context, limit int, offset int) ([]ListApplicationsRow, error)

	// ListMessages lists event-types
	ListMessages(ctx context.Context, limit int, offset int) ([]ListMessagesRow, error)

	// CreateEndpoints inserts endpoints into the database
	CreateEndpoints(ctx context.Context, endpoints []NewEndpoint) ([]CreateEndpointsRow, error)

	// ListEndpoints lists endpoints
	ListEndpoints(ctx context.Context, limit int, offset int) ([]ListEndpointsRow, error)

	// CreateEventTypes inserts event types into the database
	CreateEventTypes(ctx context.Context, eventTypes []NewEventType) ([]CreateEventTypesRow, error)

	// ListEventTypes lists event-types
	ListEventTypes(ctx context.Context, limit int, offset int) ([]ListEventTypesRow, error)

	// ListMessages lists event-types
	ListMessages(ctx context.Context, limit int, offset int) ([]ListMessagesRow, error)

	// ListSecrets lists secrets
	ListMesListSecretssages(ctx context.Context, limit int, offset int) ([]ListMesListSecretssagesRow, error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn  genericConn   // underlying Postgres transport to use
	types *typeResolver // resolve types by name
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
}

// NewQuerier creates a DBQuerier that implements Querier.
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{conn: conn, types: newTypeResolver()}
}

// NewApplication represents the Postgres composite type "new_application".
type NewApplication struct {
	TenantID  string       `json:"tenant_id"`
	RateLimit *int32       `json:"rate_limit"`
	Metadata  pgtype.JSONB `json:"metadata"`
}

// NewEndpoint represents the Postgres composite type "new_endpoint".
type NewEndpoint struct {
	Url           string       `json:"url"`
	Name          string       `json:"name"`
	ApplicationID string       `json:"application_id"`
	RateLimit     *int32       `json:"rate_limit"`
	Metadata      pgtype.JSONB `json:"metadata"`
	Description   string       `json:"description"`
	Filtertypes   []string     `json:"filtertypes"`
	Channels      []string     `json:"channels"`
}

// NewEventType represents the Postgres composite type "new_event_type".
type NewEventType struct {
	Key string `json:"key"`
}

// typeResolver looks up the pgtype.ValueTranscoder by Postgres type name.
type typeResolver struct {
	connInfo *pgtype.ConnInfo // types by Postgres type name
}

func newTypeResolver() *typeResolver {
	ci := pgtype.NewConnInfo()
	return &typeResolver{connInfo: ci}
}

// findValue find the OID, and pgtype.ValueTranscoder for a Postgres type name.
func (tr *typeResolver) findValue(name string) (uint32, pgtype.ValueTranscoder, bool) {
	typ, ok := tr.connInfo.DataTypeForName(name)
	if !ok {
		return 0, nil, false
	}
	v := pgtype.NewValue(typ.Value)
	return typ.OID, v.(pgtype.ValueTranscoder), true
}

// setValue sets the value of a ValueTranscoder to a value that should always
// work and panics if it fails.
func (tr *typeResolver) setValue(vt pgtype.ValueTranscoder, val interface{}) pgtype.ValueTranscoder {
	if err := vt.Set(val); err != nil {
		panic(fmt.Sprintf("set ValueTranscoder %T to %+v: %s", vt, val, err))
	}
	return vt
}

type compositeField struct {
	name       string                 // name of the field
	typeName   string                 // Postgres type name
	defaultVal pgtype.ValueTranscoder // default value to use
}

func (tr *typeResolver) newCompositeValue(name string, fields ...compositeField) pgtype.ValueTranscoder {
	if _, val, ok := tr.findValue(name); ok {
		return val
	}
	fs := make([]pgtype.CompositeTypeField, len(fields))
	vals := make([]pgtype.ValueTranscoder, len(fields))
	isBinaryOk := true
	for i, field := range fields {
		oid, val, ok := tr.findValue(field.typeName)
		if !ok {
			oid = unknownOID
			val = field.defaultVal
		}
		isBinaryOk = isBinaryOk && oid != unknownOID
		fs[i] = pgtype.CompositeTypeField{Name: field.name, OID: oid}
		vals[i] = val
	}
	// Okay to ignore error because it's only thrown when the number of field
	// names does not equal the number of ValueTranscoders.
	typ, _ := pgtype.NewCompositeTypeValues(name, fs, vals)
	if !isBinaryOk {
		return textPreferrer{ValueTranscoder: typ, typeName: name}
	}
	return typ
}

func (tr *typeResolver) newArrayValue(name, elemName string, defaultVal func() pgtype.ValueTranscoder) pgtype.ValueTranscoder {
	if _, val, ok := tr.findValue(name); ok {
		return val
	}
	elemOID, elemVal, ok := tr.findValue(elemName)
	elemValFunc := func() pgtype.ValueTranscoder {
		return pgtype.NewValue(elemVal).(pgtype.ValueTranscoder)
	}
	if !ok {
		elemOID = unknownOID
		elemValFunc = defaultVal
	}
	typ := pgtype.NewArrayType(name, elemOID, elemValFunc)
	if elemOID == unknownOID {
		return textPreferrer{ValueTranscoder: typ, typeName: name}
	}
	return typ
}

// newNewApplication creates a new pgtype.ValueTranscoder for the Postgres
// composite type 'new_application'.
func (tr *typeResolver) newNewApplication() pgtype.ValueTranscoder {
	return tr.newCompositeValue(
		"new_application",
		compositeField{name: "tenant_id", typeName: "text", defaultVal: &pgtype.Text{}},
		compositeField{name: "rate_limit", typeName: "int4", defaultVal: &pgtype.Int4{}},
		compositeField{name: "metadata", typeName: "jsonb", defaultVal: &pgtype.JSONB{}},
	)
}

// newNewApplicationRaw returns all composite fields for the Postgres composite
// type 'new_application' as a slice of interface{} to encode query parameters.
func (tr *typeResolver) newNewApplicationRaw(v NewApplication) []interface{} {
	return []interface{}{
		v.TenantID,
		v.RateLimit,
		v.Metadata,
	}
}

// newNewEndpoint creates a new pgtype.ValueTranscoder for the Postgres
// composite type 'new_endpoint'.
func (tr *typeResolver) newNewEndpoint() pgtype.ValueTranscoder {
	return tr.newCompositeValue(
		"new_endpoint",
		compositeField{name: "url", typeName: "text", defaultVal: &pgtype.Text{}},
		compositeField{name: "name", typeName: "text", defaultVal: &pgtype.Text{}},
		compositeField{name: "application_id", typeName: "uuid", defaultVal: &pgtype.UUID{}},
		compositeField{name: "rate_limit", typeName: "int4", defaultVal: &pgtype.Int4{}},
		compositeField{name: "metadata", typeName: "jsonb", defaultVal: &pgtype.JSONB{}},
		compositeField{name: "description", typeName: "text", defaultVal: &pgtype.Text{}},
		compositeField{name: "filtertypes", typeName: "_text", defaultVal: &pgtype.TextArray{}},
		compositeField{name: "channels", typeName: "_text", defaultVal: &pgtype.TextArray{}},
	)
}

// newNewEndpointRaw returns all composite fields for the Postgres composite
// type 'new_endpoint' as a slice of interface{} to encode query parameters.
func (tr *typeResolver) newNewEndpointRaw(v NewEndpoint) []interface{} {
	return []interface{}{
		v.Url,
		v.Name,
		v.ApplicationID,
		v.RateLimit,
		v.Metadata,
		v.Description,
		v.Filtertypes,
		v.Channels,
	}
}

// newNewEventType creates a new pgtype.ValueTranscoder for the Postgres
// composite type 'new_event_type'.
func (tr *typeResolver) newNewEventType() pgtype.ValueTranscoder {
	return tr.newCompositeValue(
		"new_event_type",
		compositeField{name: "key", typeName: "text", defaultVal: &pgtype.Text{}},
	)
}

// newNewEventTypeRaw returns all composite fields for the Postgres composite
// type 'new_event_type' as a slice of interface{} to encode query parameters.
func (tr *typeResolver) newNewEventTypeRaw(v NewEventType) []interface{} {
	return []interface{}{
		v.Key,
	}
}

// newNewApplicationArray creates a new pgtype.ValueTranscoder for the Postgres
// '_new_application' array type.
func (tr *typeResolver) newNewApplicationArray() pgtype.ValueTranscoder {
	return tr.newArrayValue("_new_application", "new_application", tr.newNewApplication)
}

// newNewApplicationArrayInit creates an initialized pgtype.ValueTranscoder for the
// Postgres array type '_new_application' to encode query parameters.
func (tr *typeResolver) newNewApplicationArrayInit(ps []NewApplication) pgtype.ValueTranscoder {
	dec := tr.newNewApplicationArray()
	if err := dec.Set(tr.newNewApplicationArrayRaw(ps)); err != nil {
		panic("encode []NewApplication: " + err.Error()) // should always succeed
	}
	return textPreferrer{ValueTranscoder: dec, typeName: "_new_application"}
}

// newNewApplicationArrayRaw returns all elements for the Postgres array type '_new_application'
// as a slice of interface{} for use with the pgtype.Value Set method.
func (tr *typeResolver) newNewApplicationArrayRaw(vs []NewApplication) []interface{} {
	elems := make([]interface{}, len(vs))
	for i, v := range vs {
		elems[i] = tr.newNewApplicationRaw(v)
	}
	return elems
}

// newNewEndpointArray creates a new pgtype.ValueTranscoder for the Postgres
// '_new_endpoint' array type.
func (tr *typeResolver) newNewEndpointArray() pgtype.ValueTranscoder {
	return tr.newArrayValue("_new_endpoint", "new_endpoint", tr.newNewEndpoint)
}

// newNewEndpointArrayInit creates an initialized pgtype.ValueTranscoder for the
// Postgres array type '_new_endpoint' to encode query parameters.
func (tr *typeResolver) newNewEndpointArrayInit(ps []NewEndpoint) pgtype.ValueTranscoder {
	dec := tr.newNewEndpointArray()
	if err := dec.Set(tr.newNewEndpointArrayRaw(ps)); err != nil {
		panic("encode []NewEndpoint: " + err.Error()) // should always succeed
	}
	return textPreferrer{ValueTranscoder: dec, typeName: "_new_endpoint"}
}

// newNewEndpointArrayRaw returns all elements for the Postgres array type '_new_endpoint'
// as a slice of interface{} for use with the pgtype.Value Set method.
func (tr *typeResolver) newNewEndpointArrayRaw(vs []NewEndpoint) []interface{} {
	elems := make([]interface{}, len(vs))
	for i, v := range vs {
		elems[i] = tr.newNewEndpointRaw(v)
	}
	return elems
}

// newNewEventTypeArray creates a new pgtype.ValueTranscoder for the Postgres
// '_new_event_type' array type.
func (tr *typeResolver) newNewEventTypeArray() pgtype.ValueTranscoder {
	return tr.newArrayValue("_new_event_type", "new_event_type", tr.newNewEventType)
}

// newNewEventTypeArrayInit creates an initialized pgtype.ValueTranscoder for the
// Postgres array type '_new_event_type' to encode query parameters.
func (tr *typeResolver) newNewEventTypeArrayInit(ps []NewEventType) pgtype.ValueTranscoder {
	dec := tr.newNewEventTypeArray()
	if err := dec.Set(tr.newNewEventTypeArrayRaw(ps)); err != nil {
		panic("encode []NewEventType: " + err.Error()) // should always succeed
	}
	return textPreferrer{ValueTranscoder: dec, typeName: "_new_event_type"}
}

// newNewEventTypeArrayRaw returns all elements for the Postgres array type '_new_event_type'
// as a slice of interface{} for use with the pgtype.Value Set method.
func (tr *typeResolver) newNewEventTypeArrayRaw(vs []NewEventType) []interface{} {
	elems := make([]interface{}, len(vs))
	for i, v := range vs {
		elems[i] = tr.newNewEventTypeRaw(v)
	}
	return elems
}

// textPreferrer wraps a pgtype.ValueTranscoder and sets the preferred encoding
// format to text instead binary (the default). pggen uses the text format
// when the OID is unknownOID because the binary format requires the OID.
// Typically occurs for unregistered types.
type textPreferrer struct {
	pgtype.ValueTranscoder
	typeName string
}

// PreferredParamFormat implements pgtype.ParamFormatPreferrer.
func (t textPreferrer) PreferredParamFormat() int16 { return pgtype.TextFormatCode }

func (t textPreferrer) NewTypeValue() pgtype.Value {
	return textPreferrer{ValueTranscoder: pgtype.NewValue(t.ValueTranscoder).(pgtype.ValueTranscoder), typeName: t.typeName}
}

func (t textPreferrer) TypeName() string {
	return t.typeName
}

// unknownOID means we don't know the OID for a type. This is okay for decoding
// because pgx call DecodeText or DecodeBinary without requiring the OID. For
// encoding parameters, pggen uses textPreferrer if the OID is unknown.
const unknownOID = 0
